### ISSUE TITLE
Implement ltrim_s()

### ISSUE THREAD

**Issue by rdipardo** [rdipardo/libmoreinttypes#1]
A forthcoming version will add `ltrim_s(char *, const char *)` to the API.
The existing `ltrim(char *)` function will become a macro wrapping `ltrim_s()`, but will still behave [as documented].

The task is to implement a public `ltrim_s` function taking two arguments: `char *`, `const char *`

1. Go [here][] for details on how the implementation is expected to work
2. Test `ltrim_s()` according to [the contribution guidelines][]

[as documented]:https://heredocs.io/libmoreinttypes/d4/d61/group__text.html#ga018d9e435e26cb8b798da9954c8ab55f
[here]: https://heredocs.io/libmoreinttypes/d4/d61/group__text.html#ga5fe2f874a54c0c90823009407f3e592a
[the contribution guidelines]: https://github.com/rdipardo/libmoreinttypes/blob/master/CONTRIBUTING.md#pull-request-process

**Comment by marcluque** [comment]
I just saw the implementation of `rtrim()` from issue #2.
For the sake of simplicity, here it is:

```C
void rtrim(char(*pstr))
{
    char* end = pstr + strlen(pstr);
    while ( isspace(*--end) );
    *(end + 1) = '\0';
}
```

I think that this could be problematic if the string pstr is not dynamically-allocated, since manipulating a stack-allocated string in C might cause undefined behavior. Can we assume that only dynamically-allocated strings are passed to `rtrim()`?
In the case of `ltrim()` it would also be wise to return a substring that is newly-allocated or clearly known as _substring_ of the originally passed string. Do you see my point? Maybe you could let me know what you think would suit best here. Also regarding the impl of `trim()` itself for issue #3.

**Comment by rdipardo** [comment]
@marcluque,
> Can we assume that only dynamically-allocated strings are passed to `rtrim()`?
> In the case of `ltrim()` it would also be wise to return a substring that is newly-allocated or clearly known as substring of the originally passed string.

The basic idea was that all the `*trim()` functions would just modify the passed-in buffer; that the buffer really __*is*__ safely mutable was taken for granted.

See the [`rtrim()` test cases](https://github.com/rdipardo/libmoreinttypes/blob/325eeff7045f6499fc81cfc3822ee0b61a537e7c/test/src/test_utils_text_h.cpp#L43) for examples of "typical" (not necessarily "correct") usage. For now, I'm trusting the test runner to find and report runtime errors.

----
> manipulating a stack-allocated string in C might cause undefined behavior

A valid concern. 

The GCC build already has [some UB checks turned on](https://github.com/rdipardo/libmoreinttypes/blob/325eeff7045f6499fc81cfc3822ee0b61a537e7c/CMakeLists.txt#L62); compiling the abovementioned test cases doesn't emit any warning, even when the argument is a literal `char[]` with automatic storage (I think).

If there are [better compiler checks](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html) available, adding them to the build would be a welcome PR.

For now, I don't know there's anything to worry about, judging from [this little demo](https://github.com/rdipardo/libmoreinttypes/blob/demo/rtrim/examples/rtrim/main.cpp). If you have `valgrind` installed and added to your system's `PATH`, you can try it out like so:

```
git clone -b demo/rtrim https://github.com/rdipardo/libmoreinttypes.git demo
cd demo
cmake -H. -B_build -DRUN_RTRIM_DEMO=1
cmake --build _build --target rtrim-demo
```

On Debian Linux, the results are something like this:

```
[ 14%] Building C object CMakeFiles/moreinttypes.dir/src/Int32.c.o
[ 28%] Building C object CMakeFiles/moreinttypes.dir/src/Int64.c.o
[ 42%] Building C object CMakeFiles/moreinttypes.dir/src/numeric.c.o
[ 57%] Building C object CMakeFiles/moreinttypes.dir/src/text.c.o
[ 71%] Linking C shared library ../build/libmoreinttypes.so
[ 71%] Built target moreinttypes
[ 85%] Building CXX object examples/rtrim/CMakeFiles/rtrim-demo.dir/main.cpp.o
[100%] Linking CXX executable ../../../build/rtrim-demo
==9359== Memcheck, a memory error detector
==9359== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==9359== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==9359== Command: /home/rob/repos/libmoreinttypes/build/rtrim-demo
==9359==
Calling rtrim() with a stack-allocated string -- char[]
-------------------------------------------------------
Before: "hello             "
After: "hello"

Calling rtrim() with a dynamically allocated string -- char*
------------------------------------------------------------
Before: "hello             "
After: "hello"
====================== FINISHED ============================
==9359==
==9359== HEAP SUMMARY:
==9359==     in use at exit: 0 bytes in 0 blocks
==9359==   total heap usage: 3 allocs, 3 frees, 73,747 bytes allocated
==9359==
==9359== All heap blocks were freed -- no leaks are possible
==9359==
==9359== For counts of detected and suppressed errors, rerun with: -v
==9359== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
[100%] Built target rtrim-demo
```

Making `valgrind` a regular step in the build process is probably a good idea (one more potential PR).

It's possible I'm missing the finer points of your observation (I don't write C/C++ often enough to call myself an expert). If you can think of a code example illustrating undefined behaviour, [CONTRIBUTING](https://github.com/rdipardo/libmoreinttypes/blob/master/CONTRIBUTING.md#pull-request-process) has exact steps for incorporating one. If some UB can be demonstrated, feel free to fix the `rtrim()` implementation accordingly.

#6 has already been opened for `ltrim()`, but I plan to wait on that until I've made some changes to the workflow as the Windows runner sometimes spins around for hours with no apparent cause.

That should give you lots of time for `trim()` and even `ltrim()`, if you find that @dogukanteber's proposal doesn't look right.
In case of overlapping implementations, the credit can be shared by a co-authored commit or similar.

**Comment by marcluque** [comment]
@rdipardo, thank you very much for taking the time to answer so thoroughly. I greatly appreciate that.
I see, in that case the concerns about stack-allocated memory should be of less importance.

> The GCC build already has some UB checks turned on; compiling the abovementioned test cases doesn't emit any warning, even when the argument is a literal char[] with automatic storage (I think).

That's true indeed, very nice that those checks are on! However, from what I know, there is a slight, but important difference between char[] and char*. C indeed stack-allocates char[], but it remains mutable. Contrary to that, char* is also stack-allocated but not mutable (see [here](https://stackoverflow.com/questions/1011455/is-it-possible-to-modify-a-string-of-char-in-c) for some SO discussion about it). I'm sorry for not clarifying that in the first place. So char[] is indeed working fine, but char* should trigger a runtime error or at least a warning.
I used the demo you linked to get the following result:
```
Calling rtrim() with a stack-allocated string -- char[]
-------------------------------------------------------
Before: "hello             "
After: "hello"

Calling rtrim() with a stack-allocated string -- char*
-------------------------------------------------------
Before: "hello             "
Segmentation fault
gmake[3]: *** [examples/rtrim/CMakeFiles/rtrim-demo.dir/build.make:105: ../build/rtrim-demo] Error 139
gmake[3]: *** Deleting file '../build/rtrim-demo'
gmake[2]: *** [CMakeFiles/Makefile2:364: examples/rtrim/CMakeFiles/rtrim-demo.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:371: examples/rtrim/CMakeFiles/rtrim-demo.dir/rule] Error 2
gmake: *** [Makefile:261: rtrim-demo] Error 2
```
Note that I used char* as in: `char* text2 = "hello             "`. It segfaults when I try to change something from `text2`.
Maybe this shows better what I was referring to.
However, the compiler already gave a warning about this (not sure if this is the same for C 😆)
```
.../main.cpp:22:19: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   22 |     char* text2 = "hello             ";
      |                   ^~~~~~~~~~~~~~~~~~~~
```


> Making valgrind a regular step in the build process is probably a good idea (one more potential PR).

But I agree, making Valgrind a regular step seems advisable. Unfortunately, I'm not very experienced with that 😅 I could still try that and let you know whether it's working for me.

> It's possible I'm missing the finer points of your observation (I don't write C/C++ often enough to call myself an expert). If you can think of a code example illustrating undefined behaviour, CONTRIBUTING has exact steps for incorporating one. If some UB can be demonstrated, feel free to fix the rtrim() implementation accordingly.

I could incorporate this example that "breaks" the current implementation. However, I'm not quite sure what would be the desired solution for this and whether this is actually as relevant as I'm kind of implying. If you say that the assumption of dynamically-allocated strings always holds, there's no reason to take this detour. In any case, I see two possible solutions to this, which regardless of the circumstances might be interesting:
1. We define two separate functions. One for mutable and one for immutable strings. The current implementations look fine to me for the dynamically-allocated case (i.e., the mutable case). Just some functions for the immutable case would be required.
2. We always _only_ read from the input string and return a _newly_ allocated string (or we make the "caller" of the function pass a buffer for the "outputted" string)

> #6 has already been opened for ltrim(), but I plan to wait on that until I've made some changes to the workflow as the Windows runner sometimes spins around for hours with no apparent cause.
That should give you lots of time for trim() and even ltrim(), if you find that @dogukanteber's proposal doesn't look right.
In case of overlapping implementations, the credit can be shared by a co-authored commit or similar.

That sounds very good, that gives us some more time to figure this out 👍🏼

**Comment by dogukanteber** [comment]
@marcluque is right. We can create two functions for each trim function, one for mutable strings and one for immutable strings. Their declaration might look like this:

```c
char* rtrim(const char* str);

void rtrim_m(char* str);
```

@marcluque has valid concerns and I actually got a segmentation fault when I tried to call the function for stack allocated string. We can offer two different types of usage for rtrim, ltrim and trim functions. What do you say @rdipardo, is it necessary to create an issue to address that problem?

**Comment by rdipardo** [comment]
> We can offer two different types of usage for rtrim, ltrim and trim functions. What do you say @rdipardo, is it necessary to create an issue to address that problem?

In other words, `*trim()`" should be "overloaded" to properly handle either kind of string. Yes to that.  

>  is it necessary to create an issue to address that problem?

No. What you're proposing already falls under the heading of "implementing" `trim()` and friends. While C truly has no concept of overloading functons, the philosphy of this project has always been to enhance to language with some object-oriented features.

**Comment by rdipardo** [comment]
@marcluque,
> the `_Generic` keyword from C:

This library currently promises [compatibility with programs in ANSI C], so `_Generic` would not be allowed in a public header.

> this would require 2 'private' (i.e., static) functions to handle either case. Hence, the interface to the user would still appear as `ltrim()`. I'm afraid that it would be a macro though.

Unfortunately, we lose the benefits of a generic caller if we wrap it with an external function: the wrapper will just cast whatever argument it gets to the specified type. Suppose, for example, the header was like this:

```c
void public(const char(*pstr)):
```

and the source was like this:

```c
static void mutable_handler(char(*pstr)) {
  printf("%s is mutable\n", pstr);
}

static void const_handler(const char(*pstr)) {
  printf("%s is NOT mutable\n", pstr);
}

#define generic_caller(x)  \
  _Generic((x), \
      const char*: const_handler, \
      char*: mutable_handler)(x)

void public(const char(*pstr)) {
  generic_caller(pstr);
}
```

In our program, calling `public()` would get the same result regardless of input:

```c
  char mutable[] = "mutable string";
  const char *constant = "constant string";
  public(mutable);
  public(constant);
```

prints out:

```
  mutable string is NOT mutable
  constant string is NOT mutable
```

I see no way around this except making 2 public versions of every `*trim()` function; the exact opposite of what we want.

Supposing we did commit to C11 as the minimum standard, the signature of `*trim()` (now a function macro) still needs changing. How do we return a shorter string to the caller given a `const char *`? Parameters can be generic; return values can't; and a function that sometimes allocates memory, sometimes not, would be a headache for the the user. It would have to look something like this:

Header file :

```c
void ltrim_rw(char (*pstr), ... /* <- allow a variable number of arguments */);
void ltrim_ro(const char (*pstr), char *target);

#define ltrim(pstr, target) _Generic((pstr), \
    const char*: ltrim_ro, \
    char*:  ltrim_rw)((pstr), target)

```

Source:

```c
void ltrim_rw(char (*pstr), ...)
{
    // directly modify `pstr`
}

void ltrim_ro(const char (*pstr), char *target)
{
    // copy a segment of `pstr` into `target`, provided it's not NULL and has room
}
```
Notice we still have to declare additional public functions to give the generic caller enough options. `ltrim()` also gains an arity of 2, so we end up with things like:

```c
char mutable[] = "mutable string";
ltrim(mutable, NULL);
```

While mandating a minimum C11 standard is no problem for contributors running Linux, where a recent compiler is always installed, it could penalize someone on Windows with only Visual Studio. Microsoft's compiler didn't have `_Generic` until [late last year], In fact, anything older than the 2015 edition can't compile this project in its current form, and things that should be universal, like a preprocessor that can parse `__STDC_VERSION__` are [recently added features].


[compatibility with programs in ANSI C]: https://github.com/rdipardo/libmoreinttypes#features
[late last year]: https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/#whats-in

[recently added features]: https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-160#note_C#:~:text=Starting%20in%20Visual%20Studio%202019%20version%2016.6,%20the%20compiler%20fully%20implements%20the%20C99%20preprocessor%20via%20the%20/Zc:preprocessor%20option.

**Comment by rdipardo** [comment]
> Do you guys happen to have any other idea?

I can think of one.

1. Re-declare `ltrim()` and friends as [variadic functions](https://en.wikipedia.org/wiki/Variadic_function#In_C):

```c
void ltrim(char(*pstr), ...);

/* . . . */

void rtrim(char(*pstr), ...);

/* . . . */

void trim(char(*pstr), ...);
```

The extra arguments (`...`) are purely optional. Calls to `rtrim()` with a single argument will compile with no modification. It's 100% backward compatible with programs already using the library.

2. For each public function, implement a pair of private `static` functions, one taking a single, mutable `char*` type, and a second taking 2 arguments: i) a target buffer of `char*` type; ii) a source string of `const char*` type. For example:

```c
static void ltrim_rw(char(*pstr))
{
    // directly modify `pstr`
}

static void ltrim_ro(char(*pstr), const char(*const_str))
{
    // copy a segment of `const_str` into `pstr`
}
```

3. Using a `va_list`, provided by the [`<stdarg.h>` header](https://www.cplusplus.com/reference/cstdarg/) (part of the [ANSI C specification](https://www.codingunit.com/ansi-c-reference-using-stdarg-h-for-variable-arguments-handling)), implement every public `*trim()` function on this basic pattern:

```c
void ltrim(char(*pstr), ...)
{
    const char* source_string = NULL;
    va_list args;
    va_start(args, pstr);

    // get the second argument, if any
    const char* source_string = va_arg(args, const char*);

    if (source_string)
    {
        // pass `pstr` and `source_string` to ltrim_ro
    }
    else
    {
        // pass `pstr` to ltrim_rw
    }

    va_end(args);
}
```

This way we're just extending functions that we already provide.
Users of the library can opt-in to the "overloaded" version by simply passing two arguments, or keep using the single-argument version, without having to rewrite their programs.

**Comment by rdipardo** [comment]
> @rdipardo, should I implement some demo of the `rtrim` and `ltrim` functions? Apart from that I'm ready to open a PR with the new functions and tests

Suggested timeline :

1. refactor `rtrim()` to catch empty strings (closing #7); a new demo program on the same PR is fine

2. Increment project version (e.g. "1.5.0") to bookmark a working impl. of a  simple `rtrim()` function

2. Make the API changes [outlined above](https://github.com/rdipardo/libmoreinttypes/issues/1#issuecomment-939512140) and edit the issues so that:

   + `ltrim()` is now 2 tasks:
       -  `ltrim_rw(char(*pstr))` 
       -  `ltrim_ro(char(*pstr), const char(*const_str)`

   + `trim()` _same as above_

   + `rtrim()` can be re-opened as it now has 1 remaining task: 
       - `rtrim_ro(char(*pstr), const char(*const_str))`.  The existing `rtrim` will be silently renamed to `rtrim_rw()` and called internally from `rtrim()`
     
    If we run out of issues (which isn't likely), we can always refactor `chomp()` on the same pattern as above.
