### ISSUE TITLE
Implement trim() and trim_s()

### ISSUE THREAD

**Issue by rdipardo** [rdipardo/libmoreinttypes#3]
A forthcoming version will add `trim_s(char *, const char *)`, as well as a [function macro] wrapping `trim_s()`, with the signature `trim(char *)`.

There are two tasks:

- [ ] implement a public `trim_s` function taking two arguments: `char *`, `const char *`
- [ ] implement a `static` `trim_rw` function taking a single argument: `char *`

1. Go [here][] for details on how the implementation is expected to work
2. Test `trim()` and `trim_s()` according to [the contribution guidelines][]

[function macro]: https://heredocs.io/libmoreinttypes/d4/d61/group__text.html#ga8b6153ef340cd45b4c0e04fbf502c077
[here]: https://heredocs.io/libmoreinttypes/d4/d61/group__text.html#gadc95ce5f179b9f993c78f71ca3c7a4de
[the contribution guidelines]: https://github.com/rdipardo/libmoreinttypes/blob/master/CONTRIBUTING.md#pull-request-process

**Comment by marcluque** [comment]
Hey there, is this still wanted? I'd like to work on this!

**Comment by rdipardo** [comment]
This and #1 can be all yours if you'd like.

Also look at [my suggestion to another contributor] about writing test cases.
The CMake scripts were recently updated to use a [unit testing framework](https://cpputest.github.io), something I forgot to mention in  [CONTRIBUTING].


[my suggestion to another contributor]:  https://github.com/rdipardo/libmoreinttypes/pull/5#issuecomment-931720018
[CONTRIBUTING]: https://github.com/rdipardo/libmoreinttypes/blob/master/CONTRIBUTING.md#pull-request-process

**Comment by marcluque** [comment]
I'd love that. Thank you very much I'll look into it and get going!
